[package]
name = "graphics-2"
description = "All of the exercises and assignments for my Computer Graphics reading course."
authors = ["Matthew Brown <matthew.e.brown.17@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
"gfx" = { path = "crates/gfx" }
"math" = { path = "crates/math" }

[workspace]
members = [
    "crates/gfx",
    "crates/math",
    "crates/math-proc",
]
