[package]
name = "gfx"
description = "A safe wrapper around raw OpenGL bindings."
authors = ["Matthew Brown <matthew.e.brown.17@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
bindings = { version = "0.1.0", path = "../bindings" }
thiserror = "1.0.43"
