[package]
name = "gloog-core"
description = "OpenGL bindings for Gloog."
authors = ["Matthew Brown <matthew.e.brown.17@gmail.com>"]
version = "0.1.0"
edition = "2021"

build = "./build.rs"

[build-dependencies]
gloog-bindgen = { version = "0.1.0", path = "../bindgen/" }
