[package]
name = "gloog-bindgen"
description = "Spec parser and bindings generator for Gloog Core."
authors = ["Matthew Brown <matthew.e.brown.17@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
roxmltree = { version = "0.18.1", default-features = false, features = ["std"] }
